#############################################################
#
# Copyright 2015 F4E | European Joint Undertaking for ITER 
#  and the Development of Fusion Energy ('Fusion for Energy')
#
# Licensed under the EUPL, Version 1.1 or - as soon they 
# will be approved by the European Commission - subsequent  
# versions of the EUPL (the "Licence"); 
# You may not use this work except in compliance with the 
# Licence. 
# You may obtain a copy of the Licence at: 
#  
# http://ec.europa.eu/idabc/eupl
#
# Unless required by applicable law or agreed to in 
# writing, software distributed under the Licence is 
# distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
# express or implied. 
# See the Licence for the specific language governing 
# permissions and limitations under the Licence. 
#
# $Id: Makefile.inc 3 2012-01-15 16:26:07Z aneto $
#
#############################################################

export MARTe2_DIR=/home/pi/MARTe2Project/GIT/MARTe2
export ROOT_DIR=/home/pi/MARTe2Project/GIT/MARTe2_embedded_tools
export MAKEDEFAULTDIR=$(ROOT_DIR)/MakeDefaults
export MARTe2_Components_DIR=/home/pi/MARTe2Project/GIT/MARTe2-components
export TARGET=armv8_rpi3


MAKEDEFAULTDIR=$(ROOT_DIR)/MakeDefaults
export SPEC_DEFS = -D_USE_HRT_PERF_MODULE

OBJSX=
SPB = $(MARTe2_DIR)/Test/Core/BareMetal.x \
    $(MARTe2_DIR)/Test/Core/Scheduler.x\
	$(MARTe2_DIR)/Test/Core/FileSystem.x\
	$(MARTe2_DIR)/Test/GTest/BareMetal.x\
	$(MARTe2_DIR)/Test/GTest/Scheduler.x\
	$(MARTe2_DIR)/Test/GTest/FileSystem.x

		


PACKAGE=

INCLUDES += -I$(MARTe2_DIR)/Lib/gtest-1.7.0/include
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L0Types
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L1Portability
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L2Objects
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L3Streams
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L4Configuration
INCLUDES += -I$(MARTe2_DIR)/Source/Core/BareMetal/L5GAMs
INCLUDES += -I$(MARTe2_DIR)/Source/Core/FileSystem/L1Portability
INCLUDES += -I$(MARTe2_DIR)/Source/Core/Scheduler/L1Portability

		
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/Core/BareMetal/MARTeCoreBTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/GTest/BareMetal/MARTeBGTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/Core/Scheduler/MARTeCoreSTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/GTest/Scheduler/MARTeSGTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/Core/FileSystem/MARTeCoreFTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/GTest/FileSystem/MARTeFGTest$(LIBEXT)
LIBRARIES_STATIC += $(ROOT_DIR)/Build/$(TARGET)/Core/MARTe2$(LIBEXT)
LIBRARIES_STATIC += /usr/lib/libgtest.a /usr/lib/libgtest_main.a 

MAKEDEFAULTDIR=$(ROOT_DIR)/MakeDefaults

include $(MAKEDEFAULTDIR)/MakeStdLibDefs.$(TARGET)

all: $(OBJS) $(SUBPROJ)   \
        $(BUILD_DIR)/MainGTest$(EXEEXT)
	echo  $(OBJS)

include $(MAKEDEFAULTDIR)/MakeStdLibRules.$(TARGET)


